version: '3.8'

services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - "8000:8000"  # Exponemos el puerto 8000 en la máquina local
    volumes:
      - .:/var/www/html  # Sincroniza los archivos del host con el contenedor
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:ZNPg+rmLfv/0b5U2qpOrXu1n5WWImViPI2M9b/XwAcM=
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=docker
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"  # Cambié el puerto para evitar conflictos en tu máquina local
    volumes:
      - db_data:/var/lib/mysql  # Almacenamiento persistente de datos

# Define un volumen para almacenar los datos de MySQL
volumes:
  db_data:

